language: node_js
node_js:
  - "stable"
  - "5"
  - "5.1"
env:
  - CXX=g++-4.8
before_script:
  - npm install -g gulp codecov codeclimate-test-reporter
script: gulp build
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - codecov
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8